### ISSUE TITLE
VTM GO

### ISSUE THREAD

**Issue by basrieter** [retrospect-addon/plugin.video.retrospect#1141]
**[Original report](https://bitbucket.org/basrieter/xbmc-online-tv/issue/1141) by Peter Notebaert (Bitbucket: [peno64](https://bitbucket.org/peno64), GitHub: [peno64](https://github.com/peno64)).**

----------------------------------------

VTM just launched a new platform: VTM GO: 
https://vtm.be/vtmgo?referer=https://nieuws.vtm.be/cultuur-media/maak-kennis-met-gratis-videoplatform-vtm-go/?referer=https://www.google.com/

It would be great if this would also be added to retrospect.

Thanks

**Comment by dagwieers** [comment]
cc @peno64 @michaelarnauts @lovecrafthp @TimTilburgs

**Comment by blowk** [comment]
This would be great if https://github.com/michaelarnauts/plugin.video.vtm.go/ can be implemented!

**Comment by dagwieers** [comment]
One of the issues that makes the VTM live stream fail has been fixed by @mediaminister and has been merged in **inputstream.adaptive**. We are waiting for it to be released.

The second major issue relates to missing MPEG-DASH Period support in **inputstream.adaptive, and there is no fix for it. Contributions are welcome.

**Comment by basrieter** [comment]
Just for my view on this. What is wrong with https://github.com/michaelarnauts/plugin.video.vtm.go/?

**Comment by peno64** [comment]
I think this is the biggest problem: https://github.com/michaelarnauts/plugin.video.vtm.go/issues/8

**Comment by dagwieers** [comment]
Then the biggest problem is that you don't understand the biggest problem :-)
It is an **inputstream.adaptive** issue, which Retrospect would also hit.
https://github.com/peak3d/inputstream.adaptive/issues/287

**Comment by peno64** [comment]
I understood from https://github.com/michaelarnauts/plugin.video.vtm.go/issues/8 that the problem is indeed in inputstream.adaptive. 

So I do not understand that you think I didn't understand, if you undestand me ;-)

**Comment by basrieter** [comment]
Ok, but if that issue is resolved now, then the add-on is functional?

**Comment by dagwieers** [comment]
There are 2 issues, one affecting live streams and one affecting normal streams (using Period support). The former issue is fixed, but the fix has not been released yet. The former issues however is a showstopper.

If we get the former issue released, we do have working live tv support and we already have a working child content offering (as it is not affected by the Period support). But the normal movies and tv shows only show the last part of the "stream" (the last Period) so that's quite dysfunctional.

**Comment by dagwieers** [comment]
BTW development has stopped until the Period-support is added. But we do plan to add a lot of functionality that we have in VRT NU, like "Mijn lijst", Watched items, channels and TV guide support. There is a lot to do, but it all depends on getting Period support added.

**Comment by basrieter** [comment]
So is there any use of adding it to Retrospect then?

**Comment by dagwieers** [comment]
If it's an identical implementation, no :-)

**Comment by peno64** [comment]
This issue was created before it was known that the vtm go addon exists and is in development. So is it then really needed or does it still have high priority? No not for me. In fact because this issue was created it was told here that it does exist and that I installed it. I uses it for my kid to watch some stuff that has fortunately no commercial breals in it because it is kids stuff anf these commercials are not allowed in such a program by Belgian law

**Comment by michaelarnauts** [comment]
I also don't see the benefit for another implementation in Retrospect. Even if @basrieter has an improvement, he can just do it in the plugin.video.vtm.go repo. The goal is indeed to add some functionalities like the vrt nu addon to more easily find the stuff you want to see.

@peno64 I agree that that Belgian law helped us a lot for the children programs :)

**Comment by basrieter** [comment]
Ok, so let's see how the original VTM GO add-on goes and then see if it is still required in Retrospect.

**Comment by TomHillaert** [comment]
So what's the status ? VTM GO not working in retrospect ?

**Comment by basrieter** [comment]
There already is a very good VTM GO add-on for Kodi. So I see no added value in adding it to Retrospect
