### ISSUE TITLE
No subtitles on tv4, Sjuan, tv12 se

### ISSUE THREAD

**Issue by basrieter** [retrospect-addon/plugin.video.retrospect#1188]
**[Original report](https://bitbucket.org/basrieter/xbmc-online-tv/issue/1188) by Johan Gustavsson (Bitbucket: [6615](https://bitbucket.org/6615), ).**

----------------------------------------

Hi, Why are NO subtitles showing on the TV4 channels \(TV4, Sjuan, and TV12\)

‌

‌

I know they have changed their api, but it should still be possible to show the subtitles…

‌

\(look at [https://uwtd.me](https://uwtd.me) for help\)

**Comment by SYSophie** [comment]
If there are issues with subtitles from Bonnier Broadcasting (tv4play,cmore) etc I would suggest looking into svtplay-dl how it has been fixed there with parsing of segmented webvtt subtitles.

Sample manifest of segmented subtitle:
`https://lbs-usp-hls-vod.cmore.se/vod/41624/tme3g3tbnki(11990130_ISMUSP).ism/tme3g3tbnki(11990130_ISMUSP)-textstream_swe=3000.m3u8`

Sample segment:
`https://lbs-usp-hls-vod.cmore.se/vod/41624/tme3g3tbnki(11990130_ISMUSP).ism/tme3g3tbnki(11990130_ISMUSP)-textstream_swe=3000-1.webvtt`

Sample of complete webvtt (NOT segmented) - Hopefully this is easier to adopt
`https://lbs-usp-hls-vod.cmore.se/vod/41624/tme3g3tbnki(11990130_ISMUSP).ism/tme3g3tbnki(11990130_ISMUSP)-textstream_swe=3000.webvtt`

Last URL contains the entire subtitle and it isn´t chopped up into segments like the other samples and I can only assume that the issue is that there's no support for segmented webvtt subtitles? If this is the case then please consider going the easy way and use the last sample to adopt support for subtitles again.

I hope this helps!

Best regards,
S.Y-Sophie
Moderator @ [uwtd.me](uwtd.me)

**Comment by basrieter** [comment]
Ok, that makes things more interesting, as it would allow me to get an unsegmented webvtt.

**Comment by SYSophie** [comment]
@basrieter Great 🚀👍

**Comment by Sopor** [comment]
Why is every dialog twice in the webvtt?
```
00:21:19.360 --> 00:21:20.000
–Jag har ett möte med Charles.
–Om vadå?

00:21:20.000 --> 00:21:23.640
–Jag har ett möte med Charles.
–Om vadå?
```

**Comment by basrieter** [comment]
They seem to just extend each other. I don't think you will notice. But I will check that once I start fixing this.

**Comment by orfeous1** [comment]
Finally, this is really great news! :)

**Comment by Sopor** [comment]
I downloaded a subtitle and tested it and it seems to work perfect 👍

**Comment by SYSophie** [comment]
@Sopor the double, triple or more occurrences are created due to that these webvtt files are parsed from the fragmented segments into one file and I guess the parser isn't merging similar lines. You won't see any difference in the final result. Sure the file is slightly bigger 50% or more then it would need to be but today I don't think this is an issue since these file are still very "light". This is an easier road to go to implement then to start parsing the segments and create a webvtt file or syncing them to each corresponding video/audio segment.

**Comment by basrieter** [comment]
Please use this zip and manually replace the Retrospect files with the newer versions inside the zip. Finally restart Kodi:

[retrospect-patch-20190831.120625.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/3562313/retrospect-patch-20190831.120625.zip)

**Comment by Sopor** [comment]
Everything seems to work as it should on all 3 channels except `Hardcore Pawn: Pantbanken` on TV12. It takes very long time to start an episode and there is no subtitle.

**Comment by basrieter** [comment]
Good to hear. No issue here with Hardcore Pawn:

![image](https://user-images.githubusercontent.com/1310443/64067705-47b2b700-cc2d-11e9-9cb4-3effb16751c9.png)

What episode?

**Comment by Sopor** [comment]
I believe it was ep 12 from 2019-08-12 and why will it take so long time before it starts?

**Comment by basrieter** [comment]
Indeed, their server has a very slow response. Was over 10 seconds here. Can't help that.

**Comment by SYSophie** [comment]
@basrieter nice work 👍

**Comment by basrieter** [comment]
I won't be pushing a separate update for this. But it will be included in the next release.
