### ISSUE TITLE
A-Z listing for Swedish Channels

### ISSUE THREAD

**Issue by basrieter** [retrospect-addon/plugin.video.retrospect#1193]
**[Original report](https://bitbucket.org/basrieter/xbmc-online-tv/issue/1193) by eefew rwgheh (Bitbucket: [strawberryreal](https://bitbucket.org/strawberryreal), ).**

----------------------------------------

I was wondering if you could add an option that make one folder of the individual folders a,b,c,d,…,z. In that way the first page will be much more clean for each channel, for instance tv4. The folder can be named A-Ö. When you click it you are presented with a list of all the folders a,b,c,d,…,z.

**Comment by Snaah** [comment]
I can't find an option for this. Am I missing something here? To me it seems that now it is always necessary with the extra step "Programmen" to browse the actual shows. I see the point of having this as an option, but not "hard coded".

Sorry for bugging you, but I got to say again "Programmen" feels awkward language wise. It has the definite article, ie "The Programs" which sounds strange as most labels otherwise have the indefinite article. In Kodi, for instance, it's "Music", "TV", "Add-ons", "Pictures" etc, not "The Music", "The TV(-programs)", "The Add-ons", "The Pictures" (likewise in Swedish). I still suggest to change it to "Program A-Ö". This is also what TV4 uses, see top page of https://www.tv4play.se/ But no biggie, of course. If I've convinced you, I can add it to a future language fix PR. :)

**Comment by basrieter** [comment]
@Snaah indeed, you need to navigate to "Programmen" now. And then, taking the settings of Retrospect into account (group if list size exceeds), it will either how A-Z, or all the shows. This is similar to the _NPO Start_ channel.

**Comment by Snaah** [comment]
@basrieter How about making it an option? Something "Group all programs of each channel into a folder". Could be connected to the settings (group by list size), like option "Yes, always", "Yes, if programs exceed [number]. Not sure what is the best not to be confusing.

"Program A-Ö"? :p I can do the minimal language PR later on so you can decide then. NRK TV has the same structure and just "A-Å" (should perhaps be changed to "Programmer A-Å". Also, the alphabetic sorting is not correct for the letters Æ, Ø and Å.)

**Comment by basrieter** [comment]
I don't really like the settings based solution, as it makes the code too complex. I basically need to take two completely different scenarios in mind, that might or might not require extra data retrieval. So that is not an option. I think I will move each channel with that many "generic" items to the same structure in the future, as it is much easier to find stuff.

Regarding the `Program A-Ö`:" this is not correct as the grouping  depends on the user settings. It actually needs to be the translation of the English "TV Shows". 

For NRK that is different, as they have the A-A structure online, so the grouping **has** to be done and cannot depend on the user. 

But I general, whats I will for the changes that require this kind of discussion I will include you guys during the coding so we can get a common view on things.

**Comment by Snaah** [comment]
You're right about the "A-Ö" part. Didn't think about that it will be incorrect if the sorting is not by name. "TV Shows" is "TV-program" in Swedish ("program" is both singular and plural). With definite article, ie "The TV Shows" it is "TV-programmen".

I think a setting for grouping or not grouping the shows would be good though. Couldn't the code for grouping shows if it exceeds [x] be used? 

NRK: Ok, I see they only have alphabetical sorting now. I discovered the  sorting of Æ, Ø and Å is (of course) done by Kodi's language settings. Changing to Norwegian it is correct, and I think that is what matters most.

Great! I'll be glad to participate, and the more we are, the better the base for your decision.
