### ISSUE TITLE
teletext subtitles on VRT.net (for ex. live channels)

### ISSUE THREAD

**Issue by bertdebondt** [retrospect-addon/plugin.video.retrospect#1223]
### Is your feature request related to a problem? Please describe

Missing teletext subtitles give a better experience

### Describe the solution you'd like

Just saw the other VRT.net kodi plugin now plays the old teletext subtitles also on the VRT's "live" channels. 
So on Flemish/Duch programs a dutch subtitle is also played. 
examples are on the "Het Journaal"

### Describe alternatives you've considered

/

### Additional context

Check function on VRT.nu kodi plugin
On the episodes sometimes a subtiltle is available, but not on the live channel version

**Comment by basrieter** [comment]
Please use this zip and manually replace the Retrospect files with the newer versions inside the zip. Finally restart Kodi. Make sure to disable the "Use HLS instead of Dash" in the Channel Options -> Settings.

[retrospect-patch-20190911.232449.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/3602795/retrospect-patch-20190911.232449.zip)
