### ISSUE TITLE
Sweden: show duration for URPlay

### ISSUE THREAD

**Issue by Snaah** [retrospect-addon/plugin.video.retrospect#1238]
### Is your feature request related to a problem? Please describe

There is a label for duration for URPlay. Would be great to have in Retrospect, besides the already present broadcast date.
### Describe the solution you'd like

That Retrospect shows duration for URPlay. It is under the label **u'duration'** in seconds.

**Comment by basrieter** [comment]
What about #1237 ?

**Comment by basrieter** [comment]
The duration is already mapped for "popular", "last chance" and "most recent". However, because they are sorted by date, Kodi will only show the dates, not duration.

I did try to add durations to the other items. Please use this zip and manually replace the Retrospect files with the newer versions inside the zip. Finally restart Kodi.

[retrospect-patch-20191016.095237.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/3733066/retrospect-patch-20191016.095237.zip)

**Comment by Snaah** [comment]
Working. Fantastic as always, Bas! Thanks.
