### ISSUE TITLE
TV3, unable to retrieve program list

### ISSUE THREAD

**Issue by orfeous1** [retrospect-addon/plugin.video.retrospect#1248]
Unable to open program list on TV3 when ive selected correct character.
Sorry for bad explanation. Guess the logfile will tell you better.

Kodi, did also crash afterwards

Unable to upload logfile here.
"Something went really wrong, and we can't process that file. Try again."
So i paste it on pastebin.
https://pastebin.com/n06nUjAa

**Comment by basrieter** [comment]
You are running a Kodi Nightly. With Python 3 being implemented stuff will break. So I will look into this. But if you want a working Kodi and add-ons stay away from the nightlies for now.

**Comment by basrieter** [comment]
I can't seem to reproduce this. Can you tell me how you can generate this? From the very first start of Kodi until it breaks?

**Comment by orfeous1** [comment]
Seems to happens on TV4 as well.. 
Recorded my TV with my phone and uploaded them on my youtube channel as unlisted.
Easier for you to see whats happening when i do it.
I did three ones.

[https://youtu.be/5n_7VaC3gZI](https://youtu.be/5n_7VaC3gZI)

[https://youtu.be/elu0ljdyFEI](https://youtu.be/elu0ljdyFEI)

[https://youtu.be/QaIONWRRez0](https://youtu.be/QaIONWRRez0)

**Comment by orfeous1** [comment]
[retrospect.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/3763219/retrospect.log)
[kodi.log](https://github.com/retrospect-addon/plugin.video.retrospect/files/3763220/kodi.log)

Allready installed latest Kodi today.
InputStream Adaptive is enabled

**Comment by orfeous1** [comment]
Seems to work sometimes and sometimes not.

**Comment by basrieter** [comment]
Yes, so there is a weird issue in Kodi here. Discussing it internally. As soon as I know more, I will let you know.

**Comment by orfeous1** [comment]
Thank you!
I will standby! :)

**Comment by bertdebondt** [comment]
> 
> 
> You are running a Kodi Nightly. With Python 3 being implemented stuff will break. So I will look into this. But if you want a working Kodi and add-ons stay away from the nightlies for now.

Hi Bas,

I also use a nightly Build from LibreEelec (Milhouse) running on a Raspberry Pi. But since build 1021 (21 okt 2019), every update of LibreElec does not working because of Python 3.
If I update to the latest nightly build (2020) it still does not work. When is Retrospect Python 3 compatible ?
Here you can find the Retrospect log file when trying to play sometime from Vier : 
http://paste.kodi.tv/iqiqozoqov

 error in detail : 
Could not playback the url
20200224 23:18:54 - [CRITICAL] - plugin.py            - 529  - | Traceback (most recent call last):
20200224 23:18:54 - [CRITICAL] - plugin.py            - 529  - |   File "/storage/.kodi/addons/plugin.video.retrospect/resources/lib/plugin.py", line 475, in play_video_item
20200224 23:18:54 - [CRITICAL] - plugin.py            - 529  - |     media_item = self.channelObject.process_video_item(media_item)
20200224 23:18:54 - [CRITICAL] - plugin.py            - 529  - |   File "/storage/.kodi/addons/plugin.video.retrospect/resources/lib/chn_class.py", line 417, in process_video_item
20200224 23:18:54 - [CRITICAL] - plugin.py            - 529  - |     return data_parser.Updater(item)
20200224 23:18:54 - [CRITICAL] - plugin.py            - 529  - |   File "/storage/.kodi/addons/plugin.video.retrospect/channels/channel.be/vier/chn_vier.py", line 454, in update_video_item_with_id
20200224 23:18:54 - [CRITICAL] - plugin.py            - 529  - |     return self.__update_video(item, data)
20200224 23:18:54 - [CRITICAL] - plugin.py            - 529  - |   File "/storage/.kodi/addons/plugin.video.retrospect/channels/channel.be/vier/chn_vier.py", line 470, in __update_video
20200224 23:18:54 - [CRITICAL] - plugin.py            - 529  - |     self.log_on()
20200224 23:18:54 - [CRITICAL] - plugin.py            - 529  - |   File "/storage/.kodi/addons/plugin.video.retrospect/channels/channel.be/vier/chn_vier.py", line 123, in log_on
20200224 23:18:54 - [CRITICAL] - plugin.py            - 529  - |     id_token = client.renew_token(refresh_token)
20200224 23:18:54 - [CRITICAL] - plugin.py            - 529  - |   File "/storage/.kodi/addons/plugin.video.retrospect/channels/channel.be/vier/awsidp.py", line 137, in renew_token
20200224 23:18:54 - [CRITICAL] - plugin.py            - 529  - |     refresh_json = JsonHelper(refresh_response)
20200224 23:18:54 - [CRITICAL] - plugin.py            - 529  - |   File "/storage/.kodi/addons/plugin.video.retrospect/resources/lib/helpers/jsonhelper.py", line 29, in __init__
20200224 23:18:54 - [CRITICAL] - plugin.py            - 529  - |     if self.data[0] not in "[{":
20200224 23:18:54 - [CRITICAL] - plugin.py            - 529  - + TypeError: 'in <string>' requires string as left operand, not int

FYI, on Vier a replay sometimes skips in time (video image freezes shortly, sound continues though, and after some seconds video image resumes also). Sometime it skips back in time and you have to manually fast forward beyond the skip back point to continue normal playback, very frustating.... probably Vier related (not Retrospect)

Regards,

Bert

**Comment by basrieter** [comment]
First: You are using the `feature-url-format` branch? Don't do that. It is far from ready for use. Stay with `master` for the latest code base. Don't use feature branches unless specifically asked for. 

Retrospect is 99,99% Python 3 compatible. However, Kodi is not. Things need to stabilize for now. 

Regarding your latest issue: it has nothing to do with Python 3. If you revert back to the latest `master` and try again on any Kodi version, I think it won't work. So please create a new issue regarding the issue with _playback_ of TV3 issues. Then include a debug retrospect.log from there.

**Comment by basrieter** [comment]
Is this only on Matrix? It seems like the http request are missing encoding

**Comment by bertdebondt** [comment]
yes it's only on Matrix

LibreELEC (Milhouse): devel-20200224210353-#0224-ge49037d (RPi2.arm)

**Comment by basrieter** [comment]
Please download branch `issue-1248` (https://github.com/retrospect-addon/plugin.video.retrospect/tree/issue-1248) and download it as zip. Then install it in Kodi and see if this works.

**Comment by basrieter** [comment]
@orfeous1 could you also check?

**Comment by orfeous1** [comment]
I have no issues on my end for TV3 havent had any issies for a very long time.
Kodi 20200215 and Retrospect v5.1.8

**Comment by basrieter** [comment]
You can find the download to test this here: https://github.com/retrospect-addon/plugin.video.retrospect/archive/issue-1248.zip

**Comment by basrieter** [comment]
Any updates here?

**Comment by orfeous1** [comment]
> Any updates here?

No, as i said.. theres no issues for me. No need for patch.
