### ISSUE TITLE
TV4play.se DRM prevents the latest programs to be played. (Fixed)

### ISSUE THREAD

**Issue by SteX68** [retrospect-addon/plugin.video.retrospect#1250]
It has something to do with:
"isDrmProtected: true"
and that is all I know, Just wanted to let this issue be known.

**Comment by basrieter** [comment]
I have no clue what you are trying to tell here. Could you please explain a a bit more? 

And instead of completely remove the bug template GitHub presented, try to fill in all the questions?

I also you would like to see a debug retrospect.log of a listing that does not show any programs? Or the videos that don't play.

**Comment by SteX68** [comment]
I am not that technical on issues, all I know is that another program that has nothing to do with retrospect has the same issue with downloading from TV 4 because of DRM and this guy is running a script to find when the "isDrmProtected:true" is being turned on, but never mind that, The issue are that the latest programs from TV 4 play can't be played in retrospect and I assume it is the same problem with the drm, Try to watch the program så mycket bättre the latest episode and you'll see what I mean, a message will pop up drm protected or something like that, hope this is enough of info. Have a great day and thank you for a great program and all the work you do.

**Comment by basrieter** [comment]
Ok, so give an example of an episode that does not play? Please provide the exact way you navigate to it?

**Comment by SteX68** [comment]
Using Retrospect going to the channel and try to start the program, The same is happening with the program Solsidan the newest episode, It do not work through Favorites either, the only way this programs work is if you go to the channels own home page to watch the latest shows, seams everything outside is being stopped by thid drm.

**Comment by basrieter** [comment]
Ok, let me look into this.

**Comment by SteX68** [comment]
Thank you.

**Comment by basrieter** [comment]
Ok, so I need some more information. I need to know what data is send for the DRM protected streams. So if you have Google Chrome you can use the Developer Tools to capture network streams. See here: https://support.zendesk.com/hc/en-us/articles/204410413-Generating-a-HAR-file-for-troubleshooting (make sure you enable the **Preserve Log options**

So go make sure you are capturing network data, then go to show that is DRM protected and start the playback. Generate a .HAR and then email that to retrospect [at] rieter [d0t] net (it might contain some data you don't want attached in public).

**Comment by SteX68** [comment]
File has been sent, was out earlier so it took awhile.

**Comment by basrieter** [comment]
Ok, got it. But the first part is not there. The har should include at least this an URL that looks like this: 

https://playback-api.b17g.net/asset/12507330?service=tv4&device=browser&protocol=hls%2Cdash&drm=widevine

Where the actual number (12507330) might differ. This url contains the majority of the data. And this call and the calls in between this URL and the actual video playback 

https://cmoreseuspdashvod30.akamaized.net/vod/a1901/w1t11vabzml(12496455_ISMUSP).ism/dash/w1t11vabzml(12496455_ISMUSP)-textstream_swe=3000-96000.dash 

Are important.

**Comment by SteX68** [comment]
So what do this mean? that TV 4 have messed something up within this files?, a bit to technical for me :) but can it be fixed or is it something TV 4 need to fix? ...or did I do something wrong?, I did exactly what you told me so I have no clue.

**Comment by basrieter** [comment]
No, what I am saying is that you need to log more in the .har file.

**Comment by SteX68** [comment]
ah...do you mean the whole show??....if so the file will be to big to send even zipped I think, plus as there is no time for me to do that today.....but if you need the whole show I could do it tomorrow...unless it become to big to send zipped...as my mail provider seams not to accept bigger files than 20meg's something to be sent.

**Comment by basrieter** [comment]
No, what you could do is go to the page of the video. Open the network manager in Chrome/Firefox. Reload the page until the video starts (you can stop then) and send that complete .har.

**Comment by bubbleboyy** [comment]
I have sent you the HAR files.

**Comment by SteX68** [comment]
Thank you bubbleboyy, I'm leaving it to you as you've already sent the files.

**Comment by basrieter** [comment]
Yes, I received more. Will look into it later.

**Comment by basrieter** [comment]
Please use this zip and manually replace the Retrospect files with the newer versions inside the zip. Finally restart Kodi.

[retrospect-patch-20191027.203709.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/3776300/retrospect-patch-20191027.203709.zip)

I think the DRM stuff should work now (but you do need Kodi Leia and Widevine)

**Comment by basrieter** [comment]
Please use this zip and manually replace the Retrospect files with the newer versions inside the zip. Finally restart Kodi.

[retrospect-patch-20191027.203709-2.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/3776567/retrospect-patch-20191027.203709-2.zip)

I think the DRM stuff should work now (but you do need Kodi Leia and Widevine)

EDIT: the previous one broke all install that were installed via the Kodi repo. Sorry!

**Comment by bubbleboyy** [comment]
I used the old patch last night. I did get a retrospect error. Its working now even with the old one.

**Comment by SteX68** [comment]
Thank you very much basrieter, Solved it for me, and thank you again bubbleboyy for the help.

**Comment by SYSophie** [comment]
Just to clarify a few things:

- @SteX68 is talking about [UWTD](uwtd.me) in his initial post, which is a software that uses a number of different tools such as svtplay-dl, youtube-dl and some other custom tools to download videos from various services which focuses on the Scandinavian VoD market.
- A script haven't been used to determine that the content has DRM this has been manually read from their API, although most of these tools mentioned above has functions that verifies if the content is protected or not to determine if it's possible to download or not.
- TV4 hasn't really messed anything up really, although it's weird that they all of a sudden has decided to encrypt certain episodes in series that previously haven't been using encryption. This is a reoccurring misstake that they have been doing for at least the last 2-3 years and a number of titels. But they usually changes these episode to none encrypted after a few hours or days.
- One possible reason for this (this is just my speculation) is that tv4 has been handling some titles manually lately when pushing them do their servers which has lead to that some misstakes has been done and wrongly labelling these titels as DRM protected.This has been done because Bonnier recently decided to not publish series such as Solsidan earlier on C-More for their premium customers as they normally do because this series is their biggest series during the year and they wanna make a stand against piracy and hopefully by doing this decreasing it. [Link to pressrelease concerning this matter.](https://www.bonnierbroadcasting.com/senaste-nytt/pressmeddelanden-innehall/2019/c-more-premiaren-av-solsidan-flyttas/)  _Sorry for the Swedish_. 

I appreciate that @basrieter has resolved the issue with Retrospect so this content can be played because the step that Bonnier has taken has lead to that many Linux and Android users won't be able to play this content due to the lack of support of Widevine on these plattforms.

**Comment by Espancor** [comment]
Hi! Thaks a lot @basrieter !! Just a question! I´m wondering if you are going to release a new update. I can´t never do right when I try to fix it up  with the files. Any tutorials about that? ;-)

**Comment by Snaah** [comment]
@Espancor [Here's a start for you](https://github.com/retrospect-addon/plugin.video.retrospect/issues/1240#issuecomment-544234439). And if you need assistance in Swedish så hjälper jag gärna till. :)

**Comment by basrieter** [comment]
Thanks for all the feedback. However, I am opening the issue again, until the sources are committed.

**Comment by basrieter** [comment]
@SYSophie Widevine works fine under Linux for Kodi. So that should be no issue.

**Comment by Espancor** [comment]
> 
> 
> @Espancor [Here's a start for you](https://github.com/retrospect-addon/plugin.video.retrospect/issues/1240#issuecomment-544234439). And if you need assistance in Swedish så hjälper jag gärna till. :)

Hej! @Snaah ! Jag läste guiden men tror inte att jag fixar det. Tack för hjälpen
Har försökt att fixa lite med filerna med lyckades inte.

**Comment by SYSophie** [comment]
@basrieter Linux works fine with Widevine L3 which restricts users to lower resolution content (SD). Same goes for Chromebooks and certain Android units. None of these mentioned supports L1

**Comment by Snaah** [comment]
@Espancor Visst är det Android TV du har? Vad är problemet? Jag guidar dig!

**Comment by Espancor** [comment]
Jag använder både kodi på tv och dator. Det jag vill lära mig är när man
vill ersätta till en ny fil.

Den tis 29 okt. 2019 17:41Snaah <notifications@github.com> skrev:

**Comment by Snaah** [comment]
@Espancor  

Vi börjar med Windows: Öppna Utforskaren, på sökvägsraden överst (ser ut som den för URL i en webbläsare), skriv in **%userprofile%\AppData\Roaming\Kodi\addons\**. Det är dit du ska extrahera filerna i den zippade filen du hämtar här.

@basrieter I'm assisting Espancor with the installation of updates not yet released. Ok to do here or do you want us to do it elsewhere? Thinking it might help others.

**Comment by basrieter** [comment]
Np to do it here, buy please do it in English then.

**Comment by Snaah** [comment]
@Espancor Is English ok for you?

**Comment by Espancor** [comment]
It´s fine for me!

**Comment by Snaah** [comment]
@Espancor Ok! So did the above work? If it did we'll continue.

**Comment by Espancor** [comment]
@Snaah I did as you said but I don´t think that I did well! Sorry!

**Comment by Snaah** [comment]
@Espancor Actually, it would be easier to show you by TeamViewer. I will be able to show you live how to do it on your computer. Do you have it installed?  Otherwise, get it [here](https://www.teamviewer.com/sv/) and reply with the code you see under "Ditt ID" (NOT the password). I will then make a login attempt, which you must say yes to. You can see everything I do, so no worries about me doing anything wrong.

**Comment by basrieter** [comment]
Just use this to "install from zip" from Kodi.

[plugin.video.retrospect-5.0.8.tv4-patch.zip](https://github.com/retrospect-addon/plugin.video.retrospect/files/3785289/plugin.video.retrospect-5.0.8.tv4-patch.zip)

**Comment by Espancor** [comment]
@Snaah It´s sound like a good idea! I just downloaded teamViewer so you can learn me how to do it, we just have to decide a date. Can you also tell me how will know if I did right with the files when a use retro addon and I click on TV4 icon? I tried to watch Solsidan but I don´t found anything.
@basrieter I did use that plugin zip but I still don´t know if it works.
Sorry and thaks for helping me!

**Comment by Snaah** [comment]
@Espancor I can help you right this minute until about 21, Swedish time. :) Otherwise, we can find another date and time. If you did do the update correctly, Retrospect will say channels have been updated and (of course) the channel/program will work. Solsidan works here, both listings and the latest episode that the latest patch in this issue fixed.

**Comment by Espancor** [comment]
Retro said that it was updated, but I don't found solsidan.
I think we can found another date and time another day.


Den tis 29 okt. 2019 20:42Snaah <notifications@github.com> skrev:

**Comment by Snaah** [comment]
@Espancor Try it again, sometimes Retrospect needs a moment. :) Yes, we'll find a better time.

**Comment by basrieter** [comment]
The "Install from zip" is a default option from Kodi: https://kodi.wiki/view/HOW-TO:Install_add-ons_from_zip_files

**Comment by bubbleboyy** [comment]
> Retro said that it was updated, but I don't found solsidan.
> I think we can found another date and time another day.
> 
> 
> Den tis 29 okt. 2019 20:42Snaah <notifications@github.com> skrev:
> …

Solsidan is geo-blocked.

**Comment by Espancor** [comment]
I used the patch plugin you gave me @basrieter . It works on android tv but not on my pc!

@bubbleboyy My settings about geo is already check as "Sweden"

**Comment by bubbleboyy** [comment]
Subtitles not working after the patch. @basrieter

**Comment by basrieter** [comment]
They work. You just need to switch it to Swedish, as there apparently are 2 tracks in the Widevine streams.

**Comment by Espancor** [comment]
Now working well! both pc and tv! I did some mixing with geo setting language and something with widevine and Voila!! thaks @basrieter  @bubbleboyy  @Snaah
