### ISSUE TITLE
MTG: Viafree - Remove title in description for items

### ISSUE THREAD

**Issue by matsarv** [retrospect-addon/plugin.video.retrospect#1423]
### Is your feature request related to a problem? Please describe

Remove title in description for items to be consistent with other swedsih channels.

### Describe the solution you'd like

  remove chn_viafree.py row ~494 in  def create_video_item(self, result_set):

                description = "%s\n\n%s" % (title, description)

### Additional context

Current:
![chn_viafreee-before](https://user-images.githubusercontent.com/46671821/93079213-10724500-f68c-11ea-9712-275ed52c14d0.png)

After:
![chn_viafree-after](https://user-images.githubusercontent.com/46671821/93079225-149e6280-f68c-11ea-980c-fbb0309cffa3.png)

**Comment by basrieter** [comment]
This is something else and in this case, it seems duplicate. But this is how it works. Consider this episode:

```
Series name: Wings of War 
Episode title: The very first episode of season 2
Season: 2
Episode: 1
Description: A very exciting episode with a good story.
```
Because it has season and episode information in the meta data, this will become: 
```
Title: Wings of War - s02e01
Description: The very first episode of season 2. A very exciting episode with a good story.
```
As you can see, I use the **series name** with **season info** as title. The actual **episode title** is moved to the description because it contains the title of the episode and should not be omitted. 

In the case from the screenshot, the episode title is "Wings of War S01E02", note the capitol "S" and "E" and the missing "-". This is the actual episode name as it comes from ViaFree and it is thus added as the first part of the description. While the title is constructed by Retrospect.

**Comment by matsarv** [comment]
I have looked in the code and I fully understand what you have described above. Still, from an viewers  point of view it's looks like it's duplicated info and for me it looks duplicated comparing from other channels.

If the episode title was better I guess it could be like this,
"Title - season/episode - text about the episode"

```
Title: Wings of War - s02e01 - The very first episode of season 2.
Description: A very exciting episode with a good story.
```

But above is not working here.

Anyhow, It's no big deal. It's upp to you to decide.

**Comment by basrieter** [comment]
So, given the limited time I have, I will leave it like this. Will focus on #1422

**Comment by Snaah** [comment]
Why close this? Isn't it better to keep it for coming work?

**Comment by basrieter** [comment]
> Why close this? Isn't it better to keep it for coming work?

No, because this is just related to inconsistent naming at their end.
