### ISSUE TITLE
License changes, and problems

### ISSUE THREAD

**Issue by comradekingu** [retrospect-addon/plugin.video.retrospect#1447]
I contributed a nb_NO translation for a GPLv3+ license.
The software itself is CC-NC, which isn't even libre software. What is going on?

**Comment by basrieter** [comment]
Yes, I am currenlty setting up Weblate, in which I gave the translations (not the add-on) a very free license (The Unlicense) that makes it easy to include it in the actual add-on. It could be that you started translating (which I greatly appreciate) while I was still setting up and was working on the licensing and GIT integration . 

The add-on is indeed licensed under CC-NC (for a long time) because I don't want any commercial use of the add-on and the CC-NC specifies that. But besides that it can be use re-used with attribution.

**Comment by comradekingu** [comment]
It looks like it is set up with a Libre plan, and in being a non-libre project, that isn't going to get approved. Moreover, you can't re-license my work, (not to something non-copyleft anyway).
What is the problem with commercial use? GitHub allows commercial use.

**Comment by basrieter** [comment]
As mentioned before: you started translating while I was setting up, I did not intend to relicense anyone's work. That was unfortunate.

Feel free to remove the contribution if that pleases you. 

I don't want any commercial reuse of my add-on. It happened in the past and that is not why I create free tools. So it's not a GitHub thing, just a 'me' thing.

**Comment by comradekingu** [comment]
Actually those weren't my translations at all, had it confused with the KODI project.
You are obviously free to do what you want with your plugin, but I would implore accepting changes under a libre software license, and keep the door open.

**Comment by basrieter** [comment]
Ok, that is no problem. I will look into the licenses and see what alternatives there are. Please do keep contributing to open source projects! All help is greatly appreciated.

**Comment by basrieter** [comment]
For your info, I am looking into switching to GPL3

**Comment by comradekingu** [comment]
I think the additional network protection of the AGPLv3+ could be useful. I don't know that it wouldn't is more how far my insight goes.
