### ISSUE TITLE
Option to remove NPO duplicate broadcast.

### ISSUE THREAD

**Issue by anonymoustly444** [retrospect-addon/plugin.video.retrospect#1560]
On NPO Start there are most duplicates of the same broadcast, i'm find that annoying.

Can you make some function to remove same name video's? The duplicates?

Thank you!

**Comment by basrieter** [comment]
I already do that. Based on name and URL. So those that seem duplicate, actually have different URL's. Do you have an example?

**Comment by anonymoustly444** [comment]
Apennoten, episode "Jeuk" is 3 times on the list, also much others are double.

**Comment by basrieter** [comment]
Ok, so they are indeed duplicate shows, but broadcasted on different days with different ID's and urls. So that is way they are not filtered out. Not something I can fix by just removing duplicate names. That will completely break NOS Journaal for instance. 

Just sort on "Date" in Kodi, so you can see what day the shows belong to.
