### ISSUE TITLE
Low bitrate since kodi v20.0

### ISSUE THREAD

**Issue by Enhancedplx** [retrospect-addon/plugin.video.retrospect#1671]
Since Kodi has been updated to version 20.0, the streams of the Dutch channel SBS6 ("KIJK") are in a very low bitrate (<360p) 
When I compare the exact same broadcast with version 18.9 there is an HD broadcast (<1080p). Settings have not been changed and are not adjustable.
Take for example the program "Lang leve de Liefde" season 5.

### To Reproduce

1. 
2.
3.

### Debuglog

The **debug** retrospect.log can be found here:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

Used versions:
- Kodi version:
- Retrospect version:

**Comment by basrieter** [comment]
Please attach a full DEBUG retrospect.log file that contains a playback. So please enable Retrospect debug logging, playback an item, then attach the retrospect.log here (don't copy paste).

**Comment by henkv1** [comment]
A workaround for this is to change the inputstream adaptive resolution to a fixed value

**Comment by basrieter** [comment]
The issue is basically related to the Input Stream Adaptive add-on. It scales the stream proportional to your resolution and that seems to be off. From Retrospect perspective I send Input Stream the MPD with multiple bitrates and tell it to playback. BUT: **as you have not provided any logfile, I don't know if you might have configured Retrospect to limit bandwidth**

**Comment by rwynands** [comment]
Is it worthwhile switching to Kodi v20.0 and will Retrospect work with it, or should we just stay with Matrix

**Comment by basrieter** [comment]
That is up to you. Retrospect will stop supporting Leia and earlier soon.

**Comment by ErikBrown2** [comment]
> Is it worthwhile switching to Kodi v20.0 and will Retrospect work with it, or should we just stay with Matrix

If you like to watch NPO and jump regularly forward or backward while viewing something then you better wait with upgrading. On NPO jumping forward or backward causes the video to freeze for some 4 to 8 seconds or so each time. It is a bit irritating and that issue is not there with Kodi 19.x. So I stick to Kodi 19.5 till the issue is solved.

**Comment by rwynands** [comment]
Got it. Thanks for the tip.

**Comment by rwynands** [comment]
Input Stream Adaptive add-on is not supported by Kodi Nexus, so live TV does not work. I had to reinstall Matrix.

**Comment by basrieter** [comment]
It is since today: Yes it is: https://github.com/xbmc/inputstream.adaptive/releases/tag/20.3.5-Nexus
